make function inline so that the symbol does not get defined several times.
GitHub Actions gives the following error message:
/home/runner/work/IOHexperimenter/IOHexperimenter/include/ioh/common/file.hpp:115: multiple definition of `ioh::common::file::utils::get_static_root[abi:cxx11]()'; CMakeFiles/test_ioh.dir/cpp/common/test_common.cpp.o:/home/runner/work/IOHexperimenter/IOHexperimenter/include/ioh/common/file.hpp:115: first defined here
From the error message, it follows that there must be actually at least two .cpp files that are merged together before compilation, that both include this file.hpp. So, if we inline the function, the code is essentially duplicated, and we're fine.